### ISSUE TITLE
Connection's process_to_queue! can double up and get in its way

### ISSUE THREAD

**Issue by phopkins** [chrisroberts/krakow#23]
I believe that if certain errors occur when writing in a `safe_socket` block, Krakow's `Connection` class will trigger a `reconnect!`, eventually leading to a second call to `connect!` and `async.process_to_queue!`.

When this happens, 2 `process_to_queue!` loops may run simultaneously, which can lead to issues. Below is some debug logging that shows 2 methods looping, where one takes the first 8 bytes of the frame content (“E_FIN_FA”) and tries to interpret it as a frame header. Once this happens, everything gets quite out-of-sorts.

```
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: Read wait for frame start
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: >>> RDY 0

<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: Read wait for frame start
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: >>> FIN 07daddb5a7e1d002

<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: >>> RDY 1

<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: <<< "\x00\x00\x00=\x00\x00\x00\x01"
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: Decoded structure: {:size=>57, :type=>1}
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: <<< "E_FIN_FA"
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: Decoded structure: {:size=>1163871813, :type=>1314866753}
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: <<< "ILED FIN 07daddb5a7e1d002 failed ID not in flight\x00\x00\x00\x84\x00\x00\x00\x02"
<Krakow::Connection:69913276569640 {172.17.0.170:4150}>: Struct: {:size=>57, :type=>1, :data=>"ILED FIN 07daddb5a7e1d002 failed ID not in flight\x00\x00\x00\x84\x00\x00\x00\x02"} Frame: <Krakow::FrameType::Error:69913210702140 [{:error=>"ILED FIN 07daddb5a7e1d002 failed ID not in flight\x00\x00\x00\x84\x00\x00\x00\x02"}]>
```

Happy to post a fix if you have ideas. The 2 solutions I came up with were to avoid re-calling `async.process_to_queue!` if `@running` is true, or to pass a socket in to `process_to_queue!` and have `while passed_in_socket == socket` as the loop. That way if the socket gets re-created it will detect that and the old call will exit.

The first might be the cleanest provided you don't feel like you risk having stale, pre-reconnect state in scope in the `process_to_queue!` call.

**Comment by chrisroberts** [comment]
https://github.com/chrisroberts/krakow/issues/22#issuecomment-74719782

**Comment by chrisroberts** [comment]
Released: https://github.com/chrisroberts/krakow/tree/v0.4.0

Thanks!

**Comment by phopkins** [comment]
Sweet! We'll try this out and let you know if we run into any problems.

Thanks for being so responsive and fixing it up.
